//
// Generated file, do not edit! Created by nedtool 5.2 from src/linklayer/simpleidealmac/MACFrameIoTorii.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __IOTORII_MACFRAMEIOTORII_M_H
#define __IOTORII_MACFRAMEIOTORII_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "inet/linklayer/common/MACAddress.h"
    #include "src/linklayer/common/eGA3Frame.h"

   typedef struct {
       inet::MACAddress MAC;
       iotorii::eGA3Frame eGA3;
   } AddressStruct;
    
    
// }}


namespace iotorii {

/**
 * Class generated from <tt>src/linklayer/simpleidealmac/MACFrameIoTorii.msg:37</tt> by nedtool.
 * <pre>
 * packet MACFrameIoTorii
 * {
 *     AddressStruct srcAddr;
 *     AddressStruct destAddr;
 * }
 * </pre>
 */
class MACFrameIoTorii : public ::omnetpp::cPacket
{
  protected:
    AddressStruct srcAddr;
    AddressStruct destAddr;

  private:
    void copy(const MACFrameIoTorii& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MACFrameIoTorii&);

  public:
    MACFrameIoTorii(const char *name=nullptr, short kind=0);
    MACFrameIoTorii(const MACFrameIoTorii& other);
    virtual ~MACFrameIoTorii();
    MACFrameIoTorii& operator=(const MACFrameIoTorii& other);
    virtual MACFrameIoTorii *dup() const override {return new MACFrameIoTorii(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual AddressStruct& getSrcAddr();
    virtual const AddressStruct& getSrcAddr() const {return const_cast<MACFrameIoTorii*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const AddressStruct& srcAddr);
    virtual AddressStruct& getDestAddr();
    virtual const AddressStruct& getDestAddr() const {return const_cast<MACFrameIoTorii*>(this)->getDestAddr();}
    virtual void setDestAddr(const AddressStruct& destAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MACFrameIoTorii& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MACFrameIoTorii& obj) {obj.parsimUnpack(b);}

} // namespace iotorii

#endif // ifndef __IOTORII_MACFRAMEIOTORII_M_H

